packages:
  # include packages in subfolders (change as required)
  - "apps/*"
  - "packages/*"
  # if required, exclude directories

# Enable hoisting of dependencies to the root node_modules
hoistPattern:
  - "*"
